// resgen — turn a directory into a resource pack.
//
//     resgen <resource-dir> <out.hpp> <out.cpp> <namespace>    source that holds the bytes
//     resgen --pack <out.pack> <resource-dir>                   the container as a file
//
// This is the build-time half of `resourced`. It is deliberately not part of the library: what a
// build step has to know and what a loader has to know are two different things — an installer
// carries no compression because it only has to unpack.
//
// It does, however, share the *format* with the library: it builds the container through
// ResourcePack and lets the library write it out, so there is one implementation of the layout and
// the two ends cannot drift apart.
//
// The generated source depends on nothing at all — not even on this library — so the bytes compile
// into a translation unit that pulls in no headers beyond <cstddef> and <span>.
#include "resourced.hpp"

#include <cstddef>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>

namespace fs = std::filesystem;

namespace {

bool read_file(const fs::path& path, scl2::bytearray& out)
{
    std::ifstream in(path, std::ios::binary | std::ios::ate);
    if (!in) return false;

    const std::streampos end = in.tellg();
    if (end < 0) return false;

    out.resize(static_cast<std::size_t>(end));
    if (end > 0) {
        in.seekg(0);
        in.read(reinterpret_cast<char*>(out.data()), static_cast<std::streamsize>(end));
        if (in.gcount() != static_cast<std::streamsize>(end)) return false;
    }
    return true;
}

// Every regular file under `root`, as a pack. The name is the path inside the directory with
// forward slashes — that string is exactly what the program will look the resource up by, so
// nothing has to be translated later.
std::optional<scl2::ResourcePack> pack_directory(const fs::path& root)
{
    if (!fs::is_directory(root)) {
        std::cerr << "resgen: not a directory: " << root.string() << "\n";
        return std::nullopt;
    }

    scl2::ResourcePack pack;
    for (const auto& entry : fs::recursive_directory_iterator(root)) {
        if (!entry.is_regular_file()) continue;

        const std::string name = entry.path().lexically_relative(root).generic_string();

        scl2::bytearray data;
        if (!read_file(entry.path(), data)) {
            std::cerr << "resgen: cannot read " << entry.path().string() << "\n";
            return std::nullopt;
        }
        pack.add(name, data);
    }

    if (pack.empty()) {
        std::cerr << "resgen: no files under " << root.string() << "\n";
        return std::nullopt;
    }
    return pack;
}

// "i18n/zh_CN.toml" -> "k_i18n_zh_CN_toml", so the name becomes a C++ identifier.
std::string as_constant_name(const std::string& resource_name)
{
    std::string out = "k_";
    for (const char c : resource_name) {
        const bool identifier = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                              || (c >= '0' && c <= '9');
        out += identifier ? c : '_';
    }
    return out;
}

int emit_source(const scl2::ResourcePack& pack, const fs::path& out_header,
                const fs::path& out_source, const std::string& name_space)
{
    const std::string note = "// Generated by resgen. Do not edit.\n";

    // ── the header: the names, as constants ──────────────────────────────
    {
        std::ofstream header(out_header, std::ios::binary);
        if (!header) {
            std::cerr << "resgen: cannot write " << out_header.string() << "\n";
            return 1;
        }

        header << note
               << "#pragma once\n\n"
               << "#include <cstddef>\n"
               << "#include <span>\n"
               << "#include <string_view>\n\n"
               << "namespace " << name_space << " {\n\n"
               << "// Every resource in the pack, under the name it is looked up with.\n";

        for (const auto& name : pack.names()) {
            header << "inline constexpr std::string_view " << as_constant_name(name)
                   << " = \"" << name << "\";\n";
        }

        header << "\n// The packed bytes, in read-only memory.\n"
               << "std::span<const std::byte> resources();\n\n"
               << "} // namespace " << name_space << "\n";
    }

    // ── the source: the bytes ────────────────────────────────────────────
    const scl2::bytearray blob = pack.dump();

    std::ofstream source(out_source, std::ios::binary);
    if (!source) {
        std::cerr << "resgen: cannot write " << out_source.string() << "\n";
        return 1;
    }

    source << note
           << "#include \"" << out_header.filename().string() << "\"\n\n"
           << "#include <cstddef>\n\n"
           << "namespace " << name_space << " {\n\n"
           << "namespace {\n\n"
           << "alignas(std::max_align_t) const unsigned char k_resources[] = {\n";

    for (std::size_t i = 0; i < blob.size(); ++i) {
        if (i % 12 == 0) source << "    ";
        const unsigned value = std::to_integer<unsigned>(blob[i]);
        source << "0x" << std::hex << std::uppercase;
        if (value < 0x10) source << '0';
        source << value << std::dec;
        source << (i + 1 == blob.size() ? '\n' : ',');
        if (i % 12 == 11 && i + 1 != blob.size()) source << '\n';
    }

    source << "};\n\n"
           << "} // namespace\n\n"
           << "std::span<const std::byte> resources() {\n"
           << "    return std::span<const std::byte>(reinterpret_cast<const std::byte*>(k_resources),\n"
           << "                                     sizeof(k_resources));\n"
           << "}\n\n"
           << "} // namespace " << name_space << "\n";

    return 0;
}

} // namespace

int main(int argc, char** argv) try {
    // ── resgen --pack <out.pack> <resource-dir> ──────────────────────────
    if (argc == 4 && std::string_view(argv[1]) == "--pack") {
        const fs::path out = argv[2];
        const auto pack = pack_directory(argv[3]);
        if (!pack) return 1;

        std::ofstream file(out, std::ios::binary);
        if (!file) {
            std::cerr << "resgen: cannot write " << out.string() << "\n";
            return 1;
        }
        pack->dump_to(file);

        std::cout << "resgen: packed " << pack->size() << " files into " << out.string() << "\n";
        return 0;
    }

    // ── resgen <resource-dir> <out.hpp> <out.cpp> <namespace> ────────────
    if (argc != 5) {
        std::cerr << "usage: resgen <resource-dir> <out.hpp> <out.cpp> <namespace>\n"
                  << "       resgen --pack <out.pack> <resource-dir>\n";
        return 2;
    }

    const std::string name_space = argv[4];
    if (name_space.empty()) {
        std::cerr << "resgen: the namespace cannot be empty\n";
        return 1;
    }

    const auto pack = pack_directory(argv[1]);
    if (!pack) return 1;

    const int result = emit_source(*pack, argv[2], argv[3], name_space);
    if (result == 0)
        std::cout << "resgen: packed " << pack->size() << " files\n";
    return result;
}
catch (const std::exception& error) {
    std::cerr << "resgen: " << error.what() << "\n";
    return 99;
}
